### ISSUE TITLE
kubeconform fails validation on null/empty fields

### ISSUE THREAD

**Issue by mustafaStakater** [yannh/kubeconform#124] opened 2022-08-25 06:09 UTC
**Problem Description:**
We are using a kubeconform to validate manifests generated as a Helm chart in our pipelines. We are using mongodb helm chart that generated a few empty / null fields in a Deployment and Service as below
![Screenshot from 2022-08-24 18-04-38](https://user-images.githubusercontent.com/101177975/186587622-260cf58e-8de9-4475-aaf3-99bee796b4e7.png)
![Screenshot from 2022-08-24 18-05-22](https://user-images.githubusercontent.com/101177975/186588074-ba9118a6-e029-4aa6-91c7-f00177903156.png)

When I run kubeconform validation 
```
kubeconform -summary -schema-location "$location" /kubeconform-data/manifest.yaml    
```

It fails with following error:
![Screenshot from 2022-08-24 18-09-13](https://user-images.githubusercontent.com/101177975/186587680-e5ca1633-9480-44d5-9a18-21b1dcc1f781.png)

This seems weird because while making resources in openshift/kubernetes empty/fields are replaced by defaults and resources are created successfully. We intended to use this in our pipelines for validation, but this makes it unusable since nulls/ empty fields can occur quite frequently.

**Comment by eyarz** [comment] 2022-08-25 06:43
I tried to reproduce this error with the following config (`nodePort: null`):
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: null
```
As you can see here, Kubeconform is passing:
![image](https://user-images.githubusercontent.com/19731161/186590033-8fe46dc9-968b-49c6-b1ae-083849a6c438.png)

I see that you're using `-schema-location "$location"` so maybe this is why I get a different result.
which schema do you use there to validate your manifest?

**Comment by mustafaStakater** [comment] 2022-08-25 06:54
We are using openshift & extract schema from openshift openapi endpoint and convert it using openshift2jsonschema utility. it generates json schemas for all resources like in the image below.
![Screenshot from 2022-08-25 11-53-05](https://user-images.githubusercontent.com/101177975/186595508-45df05b2-a0ea-4a3f-a5d3-b3bc1fd8b3cf.png)

**Comment by mustafaStakater** [comment] 2022-08-25 07:30
The above file you added is failing for my schemas, you can see schema in the repo below
https://github.com/mustafaStakater/sharing/tree/main/kubeconform/ 

Before using change $ref field on **line 27,31,35** in **service-v1.json**

**Comment by eyarz** [comment] 2022-08-25 07:53
So the OpenShift schema defines that `nodePort: null` for object type `Service`. It's the expected behavior :)

**Comment by hanzala1234** [comment] 2022-08-25 08:10
@eyarz  if that defines, it should not have failed. isn't it?

**Comment by eyarz** [comment] 2022-08-25 08:19
@hanzala1234 I forget to add "is not allowed" 🤦‍♂️. I updated my comment.
BTW, here you can find a similar issue: https://github.com/yannh/kubeconform/issues/123

**Comment by hanzala1234** [comment] 2022-08-25 08:29
thanks @eyarz  . its quite common scenario though that optional field will have null values. is that something where we can have some workaround?

**Comment by eyarz** [comment] 2022-08-25 09:45
As a workaround, you can use the `skip` flag to skip this type of k8s kind:
![image](https://user-images.githubusercontent.com/19731161/186632424-ab9c61aa-925a-40ec-a418-a03707a43a28.png)

But the best practice is to open an issue / PR in the k8s project to fix the schema.

**Comment by mustafaStakater** [comment] 2022-08-25 14:29
Service and deployments are most basic kinds, we cant ignore them because almost all applications contain services & deployments.

We arent using it locally, we intend to use it inside a pipeline as a task (extract schema from <cluster_ip>:442/openshift/openapi/v2 endpoint and validate manifests against it). manually fixing doesnt seem right to me 

Point is these manifests with null / empty fields are created successfully in openshift, so kubeconform shouldnt give an error either.

**Comment by yannh** [comment] 2022-10-16 13:21
Closing as duplicate of #123

**Closed** 2022-10-16 13:21 UTC
