### ISSUE TITLE
Unable to use the CRD example schema

### ISSUE THREAD

**Issue by Wazbat** [yannh/kubeconform#211] opened 2023-06-09 00:42 UTC
I'm trying to validate my kubernetes templates using kubeconform in a github actions workflow, however I get an error in my CI

Here is the step in my build process
```yaml
- uses: docker://ghcr.io/yannh/kubeconform:master
  with:
    entrypoint: '/kubeconform'
    args: >
      -summary -output text
      -schema-location default
      -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{ .Group }}/{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json'
      manifest-${{ matrix.name }}.yaml"
```
I have copied the url from the README, however I get the following error:
`failed initialising schema location registry: template: tpl:1:64: executing "tpl" at <.Group>: can't evaluate field Group in type struct { NormalizedKubernetesVersion string; StrictSuffix string; ResourceKind string; ResourceAPIVersion string; KindSuffix string }`

It appears that {{.Group}} is not valid as part of the template string? What should I be using there instead?

**Comment by eyarz** [comment] 2023-06-11 09:07
try without the spaces before and after each variable. 
```
-schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
```
it's a weird bug in GH workflow

**Comment by Wazbat** [comment] 2023-06-11 10:21
Ah apologies, I modified that line to make it clearer for the issue. In my workflow it's a one liner, with no spaces in the template

`        args: "-summary -output text -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' manifest-${{ matrix.name }}.yaml"`

**Comment by eyarz** [comment] 2023-06-12 07:22
are you able to reproduce this issue when running kubeconform locally?
the error that you're getting is related to an older version of kubeconform but it looks like you're using the latest version 🤷

**Comment by yannh** [comment] 2023-06-21 20:32
Ohhh very nice catch on the incorrect tag, apologies ❤️

**Comment by yannh** [comment] 2023-07-16 07:58
Closing, the Readme has been updated :bow: thanks for the report :heart:

**Closed by yannh** 2023-07-16 07:58 UTC

**Comment by CyDickey-msr** [comment] 2024-02-27 18:27
I ran into a similar issue and the fix for me was dropping the `''` around the schema links:

```
- name: Scan files with kube-conform
  if: inputs.kube_conform_checks == 'true'
  id: kube_conform_scan
  uses: docker://ghcr.io/yannh/kubeconform:v0.6.4
  with:
    entrypoint: '/kubeconform'
    args: >
      -summary 
      -strict
      -kubernetes-version ${{ inputs.kubernetes_version }}
      -schema-location default
      -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
      -schema-location https://json.schemastore.org/kustomization.json
      -output ${{ inputs.kube_conform_format }}
      ${{ inputs.directory }}
```
